/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PrayerId = IDL.Nat;
export const PrayerRequest = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PrayerResponse = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PrayerEntry = IDL.Record({
  'prayerId' : PrayerId,
  'request' : PrayerRequest,
  'user' : IDL.Principal,
  'response' : PrayerResponse,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPrayer' : IDL.Func([PrayerId], [PrayerEntry], ['query']),
  'getPrayerHistory' : IDL.Func([], [IDL.Vec(PrayerEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPrayer' : IDL.Func([IDL.Text], [PrayerId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PrayerId = IDL.Nat;
  const PrayerRequest = IDL.Record({
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PrayerResponse = IDL.Record({
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PrayerEntry = IDL.Record({
    'prayerId' : PrayerId,
    'request' : PrayerRequest,
    'user' : IDL.Principal,
    'response' : PrayerResponse,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPrayer' : IDL.Func([PrayerId], [PrayerEntry], ['query']),
    'getPrayerHistory' : IDL.Func([], [IDL.Vec(PrayerEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPrayer' : IDL.Func([IDL.Text], [PrayerId], []),
  });
};

export const init = ({ IDL }) => { return []; };